name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
      id: build_step
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Send output
      uses: distributhor/workflow-webhook@v1
      with:
        url: "https://pocstatic-api.herokuapp.com/StaticCode/build"
        json: '{ "result": "${steps.build_step.outputs.*}" }'
