name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore -fl1 "/flp1:logFile=errors_build.txt;errorsonly" -fl2 "/flp2:logFile=warnings_build.txt;warningsonly"
    - name: Get Output Build
      run: | 
        ERROS_BUILD=$(cat errors_build.txt)
        ERROS_BUILD="${ERROS_BUILD//'%'/'%25'}"
        ERROS_BUILD="${ERROS_BUILD//$'\n'/'%0A'}"
        ERROS_BUILD="${ERROS_BUILD//$'\r'/'%0D'}"
        
        WARNINGS_BUILD=$(cat warnings_build.txt)
        WARNINGS_BUILD="${WARNINGS_BUILD//'%'/'%25'}"
        WARNINGS_BUILD="${WARNINGS_BUILD//$'\n'/'%0A'}"
        WARNINGS_BUILD="${WARNINGS_BUILD//$'\r'/'%0D'}"
  
        echo "::set-output name=ErrBuild::$ERROS_BUILD"
        echo "::set-output name=WarnBuild::$WARNINGS_BUILD"
      id: build_step
    
    - name: Echo Output Build
      run: |
        echo "${{ steps.build_step.outputs.ErrBuild }}"
        echo "${{ steps.build_step.outputs.WarnBuild }}"
    
    - name: Test
      run: dotnet test --no-build 2> test_erros.txt | egrep 'Failed!|Passed!' > teste_result.txt
    
    - name: Send output
      uses: fjogeleit/http-request-action@v1
      with:
        url: "https://pocstatic-api.herokuapp.com/StaticCode/build"
        method: "POST"
        data: '{ "errors": "${{ steps.build_step.outputs.ErrBuild }}", "warnings": "${{ steps.build_step.outputs.WarnBuild }}" }'
